const product = [
  {
    id: 1,
    name: "Iced Lemon Cooler",
    image:
      "https://freshcart.codescandy.com/assets/images/products/product-img-1.jpg",
    oldPrice: 2000,
    newPrice: 1500,
    stock: true,
    category: "Dry Goods",
    rating: 4.5,
    subcategories: ["Grains & Rice", "Flour & Baking"],
    specialOffer: "Discount",
    variation: "250g",
  },
  {
    id: 2,
    name: "Classic Cola",
    image:
      "https://freshcart.codescandy.com/assets/images/products/product-img-2.jpg",
    oldPrice: 800,
    newPrice: 600,
    category: "Dry Goods",
    subcategories: ["Grains & Rice", "Canned Foods"],
    rating: 4.3,
    stock: true,
    variation: "1kg",
  },
  {
    id: 3,
    name: "Cold Brew Can",
    image:
      "https://freshcart.codescandy.com/assets/images/products/product-img-3.jpg",
    newPrice: 1200,
    category: "Meat & Poultry",
    rating: 4.6,
    subcategories: ["Chicken", "Beef"],
    specialOffer: "Special Sale",
    variation: "500g",
  },
  {
    id: 4,
    name: "Whiskey on Ice",
    image:
      "https://freshcart.codescandy.com/assets/images/products/product-img-4.jpg",
    oldPrice: 6500,
    newPrice: 6000,
    category: "Processed Goods",
    subcategories: ["Canned Products", "Instant Noodles"],
    rating: 4.7,
    variation: "3 pieces",
  },
  {
    id: 5,
    name: "Sparkling Lemon Soda",
    image:
      "https://freshcart.codescandy.com/assets/images/products/product-img-5.jpg",
    newPrice: 1000,
    category: "Dry Goods",
    subcategories: ["Spices & Seasonings", "Pasta & Noodles"],
    rating: 4.2,
    stock: true,
    variation: "1 pack",
  },
  {
    id: 6,
    name: "Vintage Rum",
    image:
      "https://freshcart.codescandy.com/assets/images/products/product-img-6.jpg",
    oldPrice: 7500,
    newPrice: 6800,
    category: "Processed Goods",
    subcategories: ["Canned Products", "Instant Noodles"],
    rating: 4.8,
    variation: "250g",
  },
  {
    id: 7,
    name: "Cold Cola Can",
    image:
      "https://freshcart.codescandy.com/assets/images/products/product-img-8.jpg",
    oldPrice: 900,
    newPrice: 750,
    category: "Dry Goods",
    subcategories: ["Spices & Seasonings", "Pasta & Noodles"],
    rating: 4.1,
    stock: true,
    variation: "500g",
  },
  {
    id: 8,
    name: "Classic Gin Tonic",
    image:
      "https://freshcart.codescandy.com/assets/images/products/product-img-2.jpg",
    newPrice: 5000,
    category: "Processed Goods",
    rating: 4.4,
    subcategories: ["Canned Products", "Instant Noodles"],
    specialOffer: "Discount",
    variation: "2kg",
  },
  {
    id: 9,
    name: "Iced Black Coffee",
    image:
      "https://freshcart.codescandy.com/assets/images/products/product-img-3.jpg",
    newPrice: 1800,
    category: "Meat & Poultry",
    subcategories: ["Chicken", "Turkey"],
    rating: 4.6,
    variation: "5kg",
  },
  {
    id: 10,
    name: "Mango Juice Can",
    image:
      "https://freshcart.codescandy.com/assets/images/products/product-img-9.jpg",
    oldPrice: 1300,
    newPrice: 1100,
    category: "Meat & Poultry",
    subcategories: ["Turkey", "Beef"],
    rating: 4.3,
    variation: "2 pieces",
  },
  {
    id: 11,
    name: "Premium Lager",
    image:
      "https://freshcart.codescandy.com/assets/images/products/product-img-3.jpg",
    oldPrice: 4200,
    newPrice: 3900,
    category: "Processed Goods",
    subcategories: ["Canned Products", "Frozen Foods"],
    rating: 4.7,
    stock: true,
    variation: "250g",
  },
  {
    id: 12,
    name: "Chilled Lemon Water",
    image:
      "https://freshcart.codescandy.com/assets/images/products/product-img-10.jpg",
    newPrice: 500,
    category: "Dry Goods",
    subcategories: ["Spices & Seasonings", "Pasta & Noodles"],
    rating: 4.0,
    variation: "250g",
  },
];
module.exports = product;
